# Definition of all trackable objects (rigid bodies) and their respective
# pose topics and TF frame name (child_frame_id).
#
# The marker ID corresponds to the *User Data* field in the Motive
#  configuration.

rigid_bodies:
    '1':
        pose: Robot_1/pose
        pose2d: Robot_1/ground_pose
        child_frame_id: Robot_1/base_link
        parent_frame_id: world
    '2':
        pose: Robot_2/pose
        pose2d: Robot_2/ground_pose
        child_frame_id: Robot_2/base_link
        parent_frame_id: world

# Configuration options at EPFL
optitrack_config:
        multicast_address: 239.255.42.99
