rigid_bodies:
    "OptitrackLink8":
        pose: OptiTrackLink8/pose
        pose2d: OptiTrackLink8/ground_pose
        odom: OptiTrackLink8/Odom
        child_frame_id: optitrack_link8
        parent_frame_id: optitrack_world
    "OptitrackTeachHandle":
        pose: OptiTrackTeachHandle/pose
        pose2d: OptiTrackTeachHandle/ground_pose
        odom: OptiTrackTeachHandle/Odom
        child_frame_id: optitrack_teach_handle
        parent_frame_id: optitrack_world

optitrack_config:
    multicast_address: 224.0.0.1
    command_port: 1510
    data_port: 9000
    enable_optitrack: true
